import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useStyles = makeStyles({
  // --- Background Animations ---
  fall: {
    animationName: {
      to: { transform: 'translateY(120vh)' },
    },
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  moveFog: {
    animationName: {
      '0%': { transform: 'translateX(-30%) scale(1)', opacity: 0 },
      '25%': { opacity: 1 },
      '75%': { opacity: 1 },
      '100%': { transform: 'translateX(100%) translateY(10%) scale(1.2)', opacity: 0 },
    },
     animationTimingFunction: 'linear',
     animationIterationCount: 'infinite',
  },
  rainbowContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '150vmax',
    height: '150vmax',
    opacity: 0,
    zIndex: 2,
    animationName: {
        from: { opacity: 0, transform: 'translateX(-50%) scale(0.8)' },
        to: { opacity: 0.9, transform: 'translateX(-50%) scale(1)' },
    },
    animationDuration: '5s',
    animationTimingFunction: 'ease-in-out',
    animationDelay: '3s',
    animationFillMode: 'forwards',
  },
  rainbowSecondaryContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '200vmax',
    height: '200vmax',
    opacity: 0,
    zIndex: 1,
    animationName: {
        '0%': { opacity: 0, transform: 'translate(-50%, -50%) scale(0.7)' },      
        '10%': { opacity: 0.3, transform: 'translate(-50%, -50%) scale(0.8)' },   
        '20%': { opacity: 0 },
        '100%': { opacity: 0 },
    },
    animationDuration: '60s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    animationDelay: '15s',
  },
  rainbow: {
    width: '100%',
    height: '100%',
    borderRadius: '50%',
    filter: 'blur(15px)',
    background: 'radial-gradient(circle, transparent 59%, rgba(255, 179, 186, 0.75) 60.5%, rgba(255, 223, 186, 0.75) 62%, rgba(255, 255, 186, 0.75) 63.5%, rgba(186, 255, 201, 0.75) 65%, rgba(186, 225, 255, 0.75) 66.5%, rgba(204, 186, 255, 0.75) 68%, rgba(230, 186, 255, 0.75) 69.5%, transparent 71%)',
    animationName: {
        '0%': { transform: 'skewY(-2deg) translateY(5vh)', opacity: 0.8 },        
        '30%': { transform: 'skewY(3deg) translateY(-10vh)', opacity: 0.3 },      
        '60%': { transform: 'skewY(-3deg) translateY(10vh)', opacity: 1.0 },      
        '80%': { transform: 'skewY(1deg) translateY(-15vh)', opacity: 0.6 },      
        '100%': { transform: 'skewY(-2deg) translateY(5vh)', opacity: 0.8 },      
    },
    animationDuration: '48s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
    animationDirection: 'alternate',
    animationDelay: '3s',
  },
  root: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100vw',
    maxHeight: '100vh',
    maxWidth: '100vw',
    color: tokens.colorNeutralForeground1,
    transition: 'background-image 0.8s ease-in-out',
    position: 'fixed',
    top: 0,
    left: 0,
    overflow: 'hidden',
  },
  rootDark: {
    backgroundColor: '#2c3e50',
    backgroundImage: 'linear-gradient(to bottom, #34495e, #2c3e50)',
  },
  rootLight: {
    backgroundColor: '#a1c4fd',
    backgroundImage: 'linear-gradient(to bottom, #a1c4fd, #c2e9fb)',
  },
  mainUI: {
    position: 'relative',
    zIndex: 10,
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    width: '100vw',
    maxHeight: '100vh',
    maxWidth: '100vw',
    overflow: 'hidden',
    backdropFilter: 'blur(1px)',
  },
});
